- hosts: localhost
  name: masterplay
  become: true
  tasks:
   - name: running master script
     script: master.sh
   - name: Install docker
     apt:
       name: docker
       state: present
   - name: Start docker
     service:
       name: docker
       state: started
       enabled: yes
- hosts: slaveservers
  name: slaveplay
  become: true
  tasks:
   - name: running slave script
     script: slave.sh      

